objects-y+=main.o led.o snippet.o
objects-$(CONFIG_USE_MOVEMENT)+=movement.o
objects-$(CONFIG_USE_PID)+=pid.o
objects-$(CONFIG_USE_COORDS)+=deltacoords.o
objects-$(CONFIG_USE_CHASSIS)+=chassis.o
objects-$(CONFIG_USE_ENCODERS)+=encoders.o
objects-$(CONFIG_USE_UART)+=uart.o
objects-$(CONFIG_USE_SENSORS)+=sensors.o
objects-$(CONFIG_USE_SERVO)+=servo.o
objects-$(CONFIG_USE_ODETECT)+=odetect.o
objects-$(CONFIG_USE_POINTS)+=points.o
objects-$(CONFIG_USE_UARTGRAB)+=uartgrab.o

subdirs-$(CONFIG_USE_PERIPHBOARD)+=periph
subdirs-$(CONFIG_USE_ACTIONS)+=robot
