#include <lib/cerebellum/stepper.h>
#include <avr/io.h>

void stepper_init()
{
        /* Configure timer */
        TCCR1A = (1<<WGM10);
        TCCR1B = (1<<WGM12) | (1<<CS10);
        TIMSK1 = (1<<TOIE1);
        
        /* Configure GPIO */
#if CONFIG_LIB_CEREBELLUM_STEPPER_NUM >= 1
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_ENABLE);
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_STEP_1);
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_DIR_1);
#endif
#if CONFIG_LIB_CEREBELLUM_STEPPER_NUM >= 2
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_STEP_2);
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_DIR_2);
#endif
#if CONFIG_LIB_CEREBELLUM_STEPPER_NUM >= 3
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_STEP_3);
        GPIO_INIT_OUT(CONFIG_LIB_CEREBELLUM_STEPPER_DIR_3);
#endif
}

