#ifndef ANTARES_LIB_CONTRIB_CEREBELLUM_BOARD_CERESTEPER_U4_H
#define ANTARES_LIB_CONTRIB_CEREBELLUM_BOARD_CERESTEPER_U4_H


#define CEREBELLUM_BOARD CereStepper-U4

/**
 * 0. Board features
 */

#define CEREBELLUM_BOARD_SUPPORT_LEDS 1
#define CEREBELLUM_BOARD_SUPPORT_DCM 1
#define CEREBELLUM_BOARD_SUPPORT_STEPPER 1

/**
 * I. LEDs definition
 */

#define CEREBELLUM_BOARD_LEDS_NUM 1

#define CEREBELLUM_BOARD_LEDS_PORT_1 PORTB /* LED port */
#define CEREBELLUM_BOARD_LEDS_PIN_1 0 /* LED pin */
#define CEREBELLUM_BOARD_LEDS_INV_1 0 /* is LED inversed */

#endif
